### ISSUE TITLE
[Issue] 어댑터, 퍼사드 패턴

### ISSUE THREAD

**Issue by seongheum-park** [SeongHeumPark/bladek#1]
## Description
- 디자인 원칙 정리
- 어댑터 패턴 정리
- 어댑터 패턴 예제 코드
- 퍼사드 패턴 정리
- 퍼사드 패턴 예제 코드

**Comment by SeongHeumPark** [comment]
## 디자인 원칙

**Comment by SeongHeumPark** [comment]
## 어댑터 패턴

**Comment by seongheum-park** [comment]
## 디자인 원칙
### 최소 지식 원칙
- 정말 친한 친구하고만 얘기하라.

### 가이드 라인
__아래와 같은 케이스로만 메소드를 호출하라!__
- 객체 자체
- 메소드에 매개변수로 전달된 객체
- 그 메소드에서 생성하거나 인스턴스를 만든 객체
- 그 객체에 속하는 구성요소

### 예시
```java
// 원칙을 따르지 않는 경우
public float getTemp() {
    Thermometer thermometer = station.getThermometer();
    return thermometer.getTemperature();
}

// 원칙을 따른 경우
public float getTemp() {
    return station.getTemprature();
}
```

### 데메테르 법칙
- __최소 지식 원칙__ 과 같은 말

### 단점
- __퍼사드 패턴__ 에서 설명

**Comment by seongheum-park** [comment]
## 어댑터 패턴
### 정의
- 인터페이스 간의 변환
- 호환성 문제를 해결

### 객체지향 원칙
- __캡슐화__
- __구성__

**Comment by SeongHeumPark** [comment]
## 객체 어댑터 vs. 클래스 어댑터
### 차이
- __구성__ vs. __상속

### 객체 어댑터 장단점
- 장점  
  + 어댑티의 서브 클래스에 대해서도 어댑터 역할을 할 수 있다.

- 단점  
  + 효율적이지 못하다. (클래스 어댑터에서 주장하는 바. 공감 1도 안감)

### 클래스 어댑터 장단점
- 장점  
  + 어댑티 전체를 다시 구현하지 않아도 된다.
  + 어댑티의 서브 클래스이기 때문에 행동을 오버라이드할 수 있다.

- 단점  
  + 특정 어댑터 클래스에만 적용된다. (즉, 유연성이 떨어짐)

**Comment by seongheum-park** [comment]
## 객체 어댑터 vs. 클래스 어댑터
### 차이
- __구성__ vs. (__상속__ || __다중 상속__)

### 객체 어댑터 장단점
- 장점  
  + 어댑티의 서브 클래스에 대해서도 어댑터 역할을 할 수 있다.

- 단점  
  + 효율적이지 못하다. (클래스 어댑터에서 주장하는 바. 공감 1도 안감)

### 클래스 어댑터 장단점
- 장점  
  + 어댑티 전체를 다시 구현하지 않아도 된다.
  + 어댑티의 서브 클래스이기 때문에 행동을 오버라이드할 수 있다. (추상화 원칙(?)에 위배되지 않는가?)

- 단점  
  + 특정 어댑터 클래스에만 적용된다. (즉, 유연성이 떨어짐)

### 정리
- __Java__ 는 __다중 상속__ 이 안되기 때문에(?) __구성__ 기반의 __객체 어댑터 기법__ 사용
- __다중 상속__ 을 지원하는 언어는 __클래스 어댑터 기법__ 사용

### 토론 거리
1. 정말 __Java__ 에서 __클래스 어댑터 기법__ 을 사용하지 못할까?  
__Java__ 는 `class`의 다중 상속은 불가하지만 `interface`는 가능함
2. __객체 어댑터__ 와 __클래스 어댑터__ 중 어느 것이 더 나은 것일까?  
정답은 없음... 취향 차 일지도...

**Comment by seongheum-park** [comment]
## 데코레이터 패턴 vs. 어댑터 패턴
### 차이점
- __책임__ or __행동__ 추가 vs. __인터페이스 변환__
- __p.290 ~ p.291__ 참고

**Comment by seongheum-park** [comment]
## 퍼사드 패턴
### 정의
- 클라이언트 <---> 퍼사드 <---> 서브시스템
- 통합되고 간단한 인터페이스 (not `interface`)
- 클라이언트와 서브시스템 간의 __약결합__ 유도 (개인적인 생각)

### 장단점
- 장점  
  + 클라이언트와 서브시스템을 분리할 수 있음
  + 즉, 클라이언트 코드를 수정할 필요가 없음
- 단점  
  + __최소 지식 원칙__ 을 지키다보면 __래퍼 클래스__ 가 늘어남
  + 시스템 복잡도와 개발 시간이 늘어남
